<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HospedajesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('hospedajes')->insert([
            [
                'id'          => 1,
                'nombre'      => 'La Floresta',
                'ubicacion'   => 'crucero de combia via marsella, Pereira, Risaralda',
                'descripcion' => 'Disfruta de un hermoso paisaje cultural, una casa principal conservada a temática del eje cafetero, cabañas construidas en guadua y madera rescatada de árboles caídos o por desastres naturales, colores vivos que resaltan la belleza de la naturaleza.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/la+floresta/img1-la-floresta.webp',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelLasMercedes/img2-las-mercedes.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelLasMercedes/img3-las-mercedes.png',
                ]),
                'municipio_id' => 1,
                'lugares'      => null,
                'coordenadas'  => '4.842520210075911, -75.75843095409881',
                'updated_at'   => '2026-02-02 23:09:43',
                'created_at'   => '2026-02-02 23:09:43',
            ],
            [
                'id'          => 2,
                'nombre'      => 'Ecohotel Monaco',
                'ubicacion'   => 'a minutos del aeropuerto y de sitios urbanos, ideal para naturaleza y descanso cercano a la ciudad.',
                'descripcion' => 'Comprometidos con el servicio en la organización de eventos empresariales, sociales y recreativos, contamos con un talento humano altamente calificado en la prestación del servicio, disponemos de una excelente infraestructura, amplia capacidad de alojamiento y un espacio campestre.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcoHotelMonaco/ecoMonaco-1.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcoHotelMonaco/ecoMonaco-2.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcoHotelMonaco/ecoMonaco-3.jpg',
                ]),
                'municipio_id' => 1,
                'lugares'      => null,
                'coordenadas'  => '4.835210014459, -75.75698009706485',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 3,
                'nombre'      => 'Ecohotel Guaduales',
                'ubicacion'   => 'Un eco-hotel en Pereira, Risaralda, ubicado en la Variante La Condina, en una zona cercana a Armenia-Pereira y a unos minutos del centro urbano de Pereira.',
                'descripcion' => 'Este alojamiento es ideal para quienes buscan un lugar tranquilo y natural, con excelentes comodidades y una ubicación estratégica para explorar Pereira y sus alrededores.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/Ecohotel+Guaduales/img1-guaduales.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/Ecohotel+Guaduales/img2-guaduales.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/Ecohotel+Guaduales/img3-guaduales.jpg',
                ]),
                'municipio_id' => 1,
                'lugares'      => null,
                'coordenadas'  => '4.764486956379701, -75.70774304783134',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 4,
                'nombre'      => 'Ecohotel Finca El Encanto',
                'ubicacion'   => 'Eco-hotel en la vereda Arabia de Pereira, Risaralda, ideal para turismo rural y naturaleza.',
                'descripcion' => 'Habitaciones con baño privado, algunas con balcón y vistas a la montaña, actividades como senderismo, desayuno americano.',
                'comentarios' => null,
                'imagenes'    => null,
                'municipio_id' => 1,
                'lugares'      => null,
                'coordenadas'  => '4.493561887795987, -75.6584415036543',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 5,
                'nombre'      => 'Ecohotel Las Mercedes',
                'ubicacion'   => 'ubicado en Combia Baja, Pereira, en un entorno natural a unos 15 min del aeropuerto internacional Matecaña y alrededor de 30 min del centro de Pereira.',
                'descripcion' => 'Las Mercedes ofrece 6 cómodas y auténticas habitaciones diseñadas con la calidez de la guadua y la madera regional, donde se fusiona el confort moderno con elementos naturales.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelLasMercedes/img1-las-mercedes.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelLasMercedes/img2-las-mercedes.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelLasMercedes/img3-las-mercedes.png',
                ]),
                'municipio_id' => 1,
                'lugares'      => null,
                'coordenadas'  => '4.856719030467163, -75.7622795036524',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 6,
                'nombre'      => 'Eecoparadise Hotel',
                'ubicacion'   => 'Finca, Corregimiento Morelia, Vereda el Retiro, Ecoparadise',
                'descripcion' => 'Alojamiento con enfoque ecológico, habitaciones confortables, actividades al aire libre.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/ecoParadise/ecoParadise-1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/ecoParadise/ecoParadise-2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/ecoParadise/ecoParadise-3.png',
                ]),
                'municipio_id' => 1,
                'lugares'      => null,
                'coordenadas'  => '4.768924195882567, -75.75505444783136',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 7,
                'nombre'      => 'Ecohotel La Milagrosa',
                'ubicacion'   => 'Hotel ecológico en Dosquebradas, departamento de Risaralda (zona metropolitana de Pereira).',
                'descripcion' => 'Ecohotel La Milagrosa ofrece habitaciones familiares con baño privado, balcón y terraza. Cuenta con piscina, jardín, restaurante, bar y Wi-Fi gratuito.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelLaMilagrosa/img1-la-milagros.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelLaMilagrosa/img2-la-milagrosa.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelLaMilagrosa/img3-la-migrasa.png',
                ]),
                'municipio_id' => 2,
                'lugares'      => null,
                'coordenadas'  => '4.833532892623716, -75.71378448830984',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 8,
                'nombre'      => 'Ecohotel Sky Green Pereira',
                'ubicacion'   => 'Eco-hotel Ecohotel Sky Green Pereira situado en la vereda La Fría, en Dosquebradas (cerca de Pereira).',
                'descripcion' => 'Este ecohotel ofrece alojamiento con jardín, aparcamiento privado gratuito, salón compartido y terraza. Dispone de restaurante, servicio de habitaciones y recepción 24 horas.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelSkyGreen/img1-Ecohotel-Sky-Green.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelSkyGreen/img2-Ecohotel-Sky-Green.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelSkyGreen/img3-Ecohotel-Sky-Green.png',
                ]),
                'municipio_id' => 2,
                'lugares'      => null,
                'coordenadas'  => '4.852685314163395, -75.70639908761282',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 9,
                'nombre'      => 'Ecohotel Paraiso Real',
                'ubicacion'   => 'Un alojamiento ecológico en Dosquebradas-Santa Rosa de Cabal (Risaralda), con acceso a zonas verdes y naturaleza.',
                'descripcion' => 'Este eco hotel cuenta con planes románticos, zonas verdes, zona de juegos, piscina térmica, restaurante bar, cabañas y un sendero ecológico.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/Ecohotel+Paraiso+Real/img1-Ecohotel-Paraiso-Real.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/Ecohotel+Paraiso+Real/img2-Ecohotel-Paraiso-Real.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/Ecohotel+Paraiso+Real/img3-Ecohotel-Paraiso-Real.png',
                ]),
                'municipio_id' => 2,
                'lugares'      => null,
                'coordenadas'  => '4.857116385810009, -75.64467797226985',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 11,
                'nombre'      => 'Hotel La Pachamama Campestre',
                'ubicacion'   => 'Un hotel y glamping campestre ubicado en Vereda la Esperanza, en Dosquebradas, Risaralda',
                'descripcion' => 'Este hotel de 4 estrellas tiene wifi gratis, servicio de habitaciones y recepción 24 horas. Alojamiento libre de humo y con buena ubicación cerca del viaducto.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/HotelPachamamaCampestre/img1-Hotel-Pachamama-Campestre.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/HotelPachamamaCampestre/img2-Hotel-Pachamama-Campestre.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/HotelPachamamaCampestre/img3-Hotel-Pachamama-Campestre.png',
                ]),
                'municipio_id' => 2,
                'lugares'      => null,
                'coordenadas'  => '4.833031589530853, -75.70574694898504',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 12,
                'nombre'      => 'Hotel Campestre Villa Mary',
                'ubicacion'   => 'Hotel campestre en Santa Rosa de Cabal, Risaralda, Colombia',
                'descripcion' => 'Dispone de wifi gratis, piscina al aire libre, jardín y salón de uso común. Ukumarí Zoo está a 30 km del alojamiento.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/HospedajeVillaMary/img1-Hospedaje-Villa-Mary.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/HospedajeVillaMary/img2-Hospedaje-Villa-Mary.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/HospedajeVillaMary/img3-Hospedaje-Villa-Mary.png',
                ]),
                'municipio_id' => 3,
                'lugares'      => null,
                'coordenadas'  => '4.864504059243341, -75.61088026432505',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 13,
                'nombre'      => 'Ecohotel Glamping El Silencio',
                'ubicacion'   => 'Alojamiento tipo eco-hotel / glamping en Vereda El Silencio, Santa Rosa de Cabal, Risaralda, Colombia.',
                'descripcion' => 'Comprometidos con el servicio en la organización de eventos empresariales, sociales y recreativos, con talento humano altamente calificado.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelGlampingElSilencio/img1-Ecohotel-Glamping-El-Silencio.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelGlampingElSilencio/img2-Ecohotel-Glamping-El-Silencio.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcohotelGlampingElSilencio/img3-Ecohotel-Glamping-El-Silencio.jpg',
                ]),
                'municipio_id' => 3,
                'lugares'      => null,
                'coordenadas'  => '4.890892644434694, -75.61140138760962',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 14,
                'nombre'      => 'Finca Campestre Villa del Campo',
                'ubicacion'   => 'Finca campestre para alojamiento en Vereda El Jazmín, Vía a Guacas, Santa Rosa de Cabal, Risaralda, Colombia.',
                'descripcion' => 'Finca Campestre Villa del Campo ofrece alojamiento con terraza o balcón, wifi gratis y TV de pantalla plana, además de piscina al aire libre y jardín.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/FincaCampestreVilladelCampo/img1-Finca-Campestre-Villa-del-Campo.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/FincaCampestreVilladelCampo/img2-Finca-Campestre-Villa-del-Campo..jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/FincaCampestreVilladelCampo/img3-Finca-Campestre-Villa-del-Campo..jpg',
                ]),
                'municipio_id' => 3,
                'lugares'      => null,
                'coordenadas'  => '4.90883615431114, -75.62157229555237',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 15,
                'nombre'      => 'Lagos de Venecia',
                'ubicacion'   => 'Alojamiento campestre y glamping en Lagos de Venecia, Vía a Guacas, Santa Rosa de Cabal, Risaralda, Colombia.',
                'descripcion' => 'Cuenta con restaurante, servicio de habitaciones, bar, jardín, piscina al aire libre abierta todo el año y terraza.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/LagosdeVenecia/img1-Lagos-de-Venecia.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/LagosdeVenecia/img2-Lagos-de-Venecia.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/LagosdeVenecia/img3-Lagos-de-Venecia.jpg',
                ]),
                'municipio_id' => 3,
                'lugares'      => null,
                'coordenadas'  => '4.890723085498422, -75.62310797966545',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 16,
                'nombre'      => 'Ecohotel Buriti',
                'ubicacion'   => 'Eco alojamiento en Santa Rosa de Cabal, Risaralda, Colombia (zona turística cerca de termales).',
                'descripcion' => 'Ukumarí Zoo está a 30 km del alojamiento, y el aeropuerto internacional Matecaña está a 20 km. Ofrece servicio de traslado y conexión Wi-Fi.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcoHotelBuriti/buriti-1.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcoHotelBuriti/buriti-2.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/EcoHotelBuriti/buriti-3.jpg',
                ]),
                'municipio_id' => 3,
                'lugares'      => null,
                'coordenadas'  => '4.86552275780362, -75.61012977966753',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 17,
                'nombre'      => 'Cántaros Glamping',
                'ubicacion'   => 'Glamping ecológico en Santa Rosa de Cabal – Termales San Vicente, Risaralda, Colombia.',
                'descripcion' => 'Cántaros Glamping está en Santa Rosa de Cabal, ofrece alojamiento con wifi gratis, jardín con terraza y vistas al jardín.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/C%C3%A1ntarosGlamping/img1-C%C3%A1ntaros-Glamping.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/C%C3%A1ntarosGlamping/img2-C%C3%A1ntaros-Glamping.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/C%C3%A1ntarosGlamping/img3-C%C3%A1ntaros-Glamping.jpg',
                ]),
                'municipio_id' => 3,
                'lugares'      => null,
                'coordenadas'  => '4.883925131744478, -75.58791890240715',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 18,
                'nombre'      => 'Hotel El Dorado',
                'ubicacion'   => 'Hotel en Quinchía, Risaralda, Colombia.',
                'descripcion' => 'Hotel El Dorado se encuentra en Quinchía y dispone de bar y terraza. Ofrece habitaciones familiares y servicio de habitaciones.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/Eldorado/Dorado-1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/Eldorado/Dorado-2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/Eldorado/Dorado-3.png',
                ]),
                'municipio_id' => 4,
                'lugares'      => null,
                'coordenadas'  => '5.3383962866743655, -75.72922413359787',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 19,
                'nombre'      => 'Hotel Quinchía',
                'ubicacion'   => 'Hotel céntrico en Quinchía, Risaralda, Colombia (municipio cafetero).',
                'descripcion' => 'Hotel Quinchía se encuentra en Quinchía. El alojamiento ofrece salón de uso común, servicio de habitaciones y servicio de organización de tours.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/HotelQuinchia/hQuinchia-1.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/HotelQuinchia/hQuinchia-2.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/HotelQuinchia/hQuinchia-3.jpg',
                ]),
                'municipio_id' => 4,
                'lugares'      => null,
                'coordenadas'  => '5.339421155817943, -75.72809664948618',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 20,
                'nombre'      => 'Casa Blanca',
                'ubicacion'   => 'Alojamiento de tipo casa/villa en Quinchía, Risaralda, Colombia, con vistas a los paisajes de la región cafetera desde una terraza, ideal para grupos o estancias relajadas.',
                'descripcion' => 'Casa Blanca se encuentra en Quinchía y ofrece jardín, wifi gratis, cocina compartida y salón de uso común. Este alojamiento ofrece parking privado gratuito y acceso a un balcón.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/casablanca/img1-casa-blanca.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/casablanca/img2-casa-blanca.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/casablanca/img3-casa-blanca.png',
                ]),
                'municipio_id' => 4,
                'lugares'      => null,
                'coordenadas'  => '5.336740004456793, -75.72562964081256',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 21,
                'nombre'      => 'Finca El Encuentro',
                'ubicacion'   => 'Finca de alojamiento en Vereda La Oriental, Marsella, Risaralda, Colombia.',
                'descripcion' => 'Finca el Encuentro Eje Cafetero tiene piscina, jardín, terraza y vistas a la montaña. Está en Marsella y ofrece alojamiento con wifi y parking privado, ambos gratuitos.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/Finca+el+Encuentro/img1-Finca-el-Encuentro.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/Finca+el+Encuentro/img2-Finca-el-Encuentro.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/Finca+el+Encuentro/img3-Finca-el-Encuentro.png',
                ]),
                'municipio_id' => 5,
                'lugares'      => null,
                'coordenadas'  => '4.891233762247731, -75.74865571884067',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 22,
                'nombre'      => 'Finca La Lucitania',
                'ubicacion'   => null,
                'descripcion' => 'Casa La Lucitania se encuentra en Marsella, a 36 km de Ukumarí Zoo, a 29 km de Villa Olímpica de Pereira y a 30 km de Centro de Convenciones Expofuturo.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/CASAFINCALUCITANIA/img1casa-finca-lucitania.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/CASAFINCALUCITANIA/img2casa-finca-lucitania.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/CASAFINCALUCITANIA/img3-casa-finca-lucitania.jpg',
                ]),
                'municipio_id' => 5,
                'lugares'      => null,
                'coordenadas'  => '4.988539994479356, -75.73681071793578',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
            [
                'id'          => 27,
                'nombre'      => 'Hotel Quinchía (Guatica)',
                'ubicacion'   => 'Hotel céntrico en Quinchía, Risaralda, Colombia (municipio cafetero).',
                'descripcion' => 'El alojamiento ofrece salón de uso común, servicio de habitaciones y servicio de organización de tours, a 8,7 km de Guatica.',
                'comentarios' => null,
                'imagenes'    => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/HotelQuinchia/hQuinchia-1.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/HotelQuinchia/hQuinchia-2.jpg',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Hospedajes/HotelQuinchia/hQuinchia-3.jpg',
                ]),
                'municipio_id' => 8,
                'lugares'      => null,
                'coordenadas'  => '5.339421155817943, -75.72809664948618',
                'updated_at'   => null,
                'created_at'   => '2025-12-01 11:23:45',
            ],
        ]);
    }
}