<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LugaresSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('lugares')->insert([
            [
                'id'              => 1,
                'nombre'          => 'BIOPARQUE UKUMARÍ',
                'descripcion'     => 'El Bioparque Ukumarí, en Pereira, es un centro de conservación y educación ambiental con bioregiones que recrean hábitats naturales. Alberga especies como pumas, rinocerontes y monos, promoviendo el respeto por la biodiversidad',
                'coordenadas'     => '4.801875003216918, -75.8123357153258',
                'ubicacion'       => 'Kilómetro 14 vía Pereira – Cerritos, Risaralda pereira',
                'municipio_id'    => 1,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/BIOPARQUEUKUMARI/Ukumari2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/BIOPARQUEUKUMARI/Ukumari1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/BIOPARQUEUKUMARI/Ukumari3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => '2026-02-17 17:14:08',
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 2,
                'nombre'          => 'LAGUNA DEL OTÚN',
                'descripcion'     => 'La Laguna del Otún, ubicada en el Parque Natural Los Nevados, en Risaralda, es un lago a más de 3.900 m de altitud. Sus aguas alimentan el río Otún y es hogar de diversas especies, como el pato andino y el frailejón.',
                'coordenadas'     => '4.7758, -75.4147',
                'ubicacion'       => 'Parque Nacional Natural Los Nevados, acceso por El Cedral, Pereira, Risaralda.',
                'municipio_id'    => 1,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/LAGUNADELOTUN/LagunaOtun1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/LAGUNADELOTUN/LagunaOtun2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/LAGUNADELOTUN/LagunaOtun3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => '2026-02-03 04:27:44',
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 3,
                'nombre'          => 'SENDERO YARUMAL',
                'descripcion'     => 'El Sendero Ecológico Yarumal, en Risaralda, es una ruta de ecoturismo que atraviesa bosques de niebla, permitiendo la observación de flora y fauna nativa. Es ideal para el senderismo y la conexión con la naturaleza.',
                'coordenadas'     => '4.7923, -75.7601',
                'ubicacion'       => 'Sector Serranía La Marcada, Dosquebradas, Risaralda.',
                'municipio_id'    => 1,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/SENDEROYARUMAL/senderoYaruma.webp',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 4,
                'nombre'          => 'JARDÍN BOTANICO UTP',
                'descripcion'     => 'El Jardín Botánico de la UTP, en Pereira, es un espacio de conservación y educación ambiental con senderos ecológicos, diversidad de flora y fauna, y áreas destinadas a la investigación y el ecoturismo.',
                'coordenadas'     => '4.7912, -75.6901',
                'ubicacion'       => 'Dentro del campus de la Universidad Tecnológica de Pereira, Risaralda.',
                'municipio_id'    => 1,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/JARDINBOTANICOUTP/BotanicoUTP1.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => '2025-12-15 16:34:26',
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 5,
                'nombre'          => 'PARQUE NATURAL UCUMARÍ',
                'descripcion'     => 'El Parque Natural Ucumari, en Risaralda, Colombia, es una reserva ecológica con bosques de niebla, rica biodiversidad y senderos ideales para el ecoturismo, la observación de aves y el contacto con la naturaleza.',
                'coordenadas'     => '4.7615, -75.5640',
                'ubicacion'       => 'Kilómetro 14 vía Pereira – Cerritos, Risaralda.',
                'municipio_id'    => 1,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/PARQUENATURALUCUMARI/Ucumari1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/PARQUENATURALUCUMARI/Ucumari2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/PARQUENATURALUCUMARI/Ucumari3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 6,
                'nombre'          => 'DIVISA DE DON JUAN',
                'descripcion'     => 'La Divisa de Don Juan, en Pereira, es una finca que ofrece experiencias inmersivas sobre el proceso del café. Ubicada en el Paisaje Cultural Cafetero, combina tradición, sostenibilidad y recorridos guiados, para conocer de cerca la producción cafetera y disfrutar de la naturaleza.',
                'coordenadas'     => '5.0069, -76.0142',
                'ubicacion'       => 'Centro poblado La Divisa, vereda San Juan, Santa Rosa de Cabal, Risaralda.',
                'municipio_id'    => 1,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/DIVISADONJUAN/divisaJuan1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/DIVISADONJUAN/divisaJuan2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/DIVISADONJUAN/divisaJuan3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 7,
                'nombre'          => 'ALTO DEL NUDO',
                'descripcion'     => 'El Alto del Nudo, ubicado entre Pereira y Dosquebradas, es una importante reserva natural de la Cordillera Occidental. Con bosques nativos, senderos ecológicos y gran biodiversidad, es un lugar ideal para el ecoturismo, el avistamiento de aves y la conexión con la naturaleza.',
                'coordenadas'     => '4.8667, -75.7167',
                'ubicacion'       => 'Serranía El Nudo, acceso por la vereda El Nudo o El Chaquiro, Dosquebradas, Risaralda.',
                'municipio_id'    => 2,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/ALTODELNUDO/Altoelnudo1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/ALTODELNUDO/Altoelnudo2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/ALTODELNUDO/Altoelnudo3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 8,
                'nombre'          => 'BONITA FARM',
                'descripcion'     => 'Es un Bioparque y Mariposario establecido como un centro de interpretación y de seducción ambiental. Está desarrollado en una finca cafetera, donde se aprovecha toda una serie de atractivos como la biodiversidad y el hermoso y particular paisaje que lo rodea.',
                'coordenadas'     => '4.7958, -75.7275',
                'ubicacion'       => 'Bioparque Mariposario Bonita Farm, Dosquebradas, Risaralda.',
                'municipio_id'    => 2,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/BONITAFARM/BonitaFarm1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/BONITAFARM/BonitaFarm2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/BONITAFARM/BonitaFarm3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 9,
                'nombre'          => 'LAGO DE LA PRADERA',
                'descripcion'     => 'Este parque urbano combina naturaleza y recreación, con lagos, senderos, zonas deportivas y actividades como canotaje y canopy.',
                'coordenadas'     => '4.8329, -75.6669',
                'ubicacion'       => 'Zona urbana, cerca del Parque Principal de Marsella, Risaralda.',
                'municipio_id'    => 2,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/LAGODELAPRADERA/LagoPradera1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/LAGODELAPRADERA/LagoPradera2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/LAGODELAPRADERA/LagoPradera3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 10,
                'nombre'          => 'Termales de Santa Rosa de Cabal',
                'descripcion'     => 'Disfruta de piscinas naturales de aguas termales, ideales para la hidroterapia y la relajación. Este complejo, con spa y cascadas, es el principal atractivo de la región y se nutre del influjo volcánico de Los Nevados.',
                'coordenadas'     => '4.8731, -75.6195',
                'ubicacion'       => 'Km 9 Vereda San Ramón, Santa Rosa de Cabal, Risaralda.',
                'municipio_id'    => 3,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/TERMALES_SANTAROSA/TermalesSantaRosa1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/TERMALES_SANTAROSA/TermalesSantaRosa2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/TERMALES_SANTAROSA/TermalesSantaRosa3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 11,
                'nombre'          => 'Termales de San Vicente',
                'descripcion'     => 'A pocos kilómetros, este balneario ofrece una experiencia similar a los termales de Santa Rosa, combinando relajación con actividades de aventura como rappel y canopy, permitiéndote disfrutar de la naturaleza en un entorno único.',
                'coordenadas'     => '5.0194, -75.4528',
                'ubicacion'       => 'Km 18 Vía Toboganes, Santa Rosa de Cabal, Risaralda.',
                'municipio_id'    => 3,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/TERMALES_SANVICENTE/TermalesSanVicente1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/TERMALES_SANVICENTE/TermalesSanVicente2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/TERMALES_SANVICENTE/TermalesSanVicente3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 12,
                'nombre'          => 'Los chorros de Don Lolo',
                'descripcion'     => 'Ubicada en un entorno natural privilegiado, esta cascada es perfecta para quienes disfrutan del senderismo y la observación de la biodiversidad, ofreciendo un espectáculo natural impresionante.',
                'coordenadas'     => '4.8583, -75.5972',
                'ubicacion'       => 'Sendero de acceso por la Vía Termales de San Vicente, Santa Rosa de Cabal, Risaralda.',
                'municipio_id'    => 3,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/LOSCHORROS_DONLOLO/chorrosDonlolo1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/LOSCHORROS_DONLOLO/chorrosDonlolo2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/LOSCHORROS_DONLOLO/chorrosDonlolo3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 13,
                'nombre'          => 'Paramillos de Santa Rosa',
                'descripcion'     => 'Este estratovolcán, parte del Parque Nacional Natural Los Nevados, destaca por sus fuentes termales y las vistas panorámicas que regala, siendo un atractivo geológico y natural imperdible.',
                'coordenadas'     => '4.7877, -75.4652',
                'ubicacion'       => 'Parque Natural Regional Paramillo de Santa Rosa, Risaralda.',
                'municipio_id'    => 3,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/PARAMILLOS_SANTAROSA/ParamillosSantaRosa1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/PARAMILLOS_SANTAROSA/ParamillosSantaRosa2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/PARAMILLOS_SANTAROSA/ParamillosSantaRosa3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 14,
                'nombre'          => 'Basílica Señora de Las Victorias',
                'descripcion'     => 'Este emblemático templo, con más de 150 años de historia, es un importante referente religioso y cultural en Santa Rosa, reflejando la tradición y el legado de la región.',
                'coordenadas'     => '4.9493, -75.9611',
                'ubicacion'       => 'Carrera 6 con Calle 7, Parque Principal de Santuario, Risaralda.',
                'municipio_id'    => 3,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/BASILICA_SANTA+ROSA/basilica1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/BASILICA_SANTA+ROSA/basilica2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/BASILICA_SANTA+ROSA/basilica3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 15,
                'nombre'          => 'CERRO GOBIA',
                'descripcion'     => 'El Cerro Gobia en Quinchía es un sitio ecoturístico con senderos, miradores y bosques andinos. Ideal para caminatas, avistamiento de aves y disfrutar de la biodiversidad, es gestionado por comunidades locales que promueven el turismo sostenible.',
                'coordenadas'     => '5.3400, -75.7720',
                'ubicacion'       => 'Vereda Naranjal Alto, Quinchía, Risaralda.',
                'municipio_id'    => 4,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CERROGOBIA/cerroGobia1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CERROGOBIA/cerroGobia2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CERROGOBIA/cerroGobia3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 16,
                'nombre'          => 'CERRO BATERO',
                'descripcion'     => 'Este cerro ubicado en Quinchía, Risaralda es un sitio sagrado en la mitología indígena local. Ofrece rutas de senderismo y actividades de aventura, como descenso controlado por cuerdas junto a la cascada Lágrimas de Mitchua.',
                'coordenadas'     => '5.2730, -75.7330',
                'ubicacion'       => 'Parque Natural Cerro Batero, cerca al casco urbano de Quinchía, Risaralda.',
                'municipio_id'    => 4,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CERROBATERO/CerroBatero1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CERROBATERO/CerroBatero2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CERROBATERO/CerroBatero3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 17,
                'nombre'          => 'CUEVA DEL INDIO',
                'descripcion'     => 'La Cueva del Indio en Quinchía, Risaralda, es un lugar para explorar formaciones rocosas, practicar espeleología y observar murciélagos, todo en un entorno natural único. Es ideal para quienes buscan aventura y contacto con la naturaleza.',
                'coordenadas'     => '5.3089, -75.7366',
                'ubicacion'       => 'Zona rural cercana al casco urbano de Quinchía, Risaralda.',
                'municipio_id'    => 4,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CUEVADELINDIO/cuevaIndio1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CUEVADELINDIO/cuevaIndio2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CUEVADELINDIO/cuevaIndio3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 18,
                'nombre'          => 'RESERVA NATURAL LA NONA',
                'descripcion'     => 'La Reserva natural La Nona es una reserva que protege nacimientos de agua y bosques andinos. Ideal para caminatas, avistamiento de aves y conexión con la naturaleza. Ofrece paisajes tranquilos y una gran diversidad de fauna y flora.',
                'coordenadas'     => '4.886788817078453, -75.72232766441785',
                'ubicacion'       => 'Reserva Forestal Protectora Regional La Nona, Vereda El Rayo o La Convención, Marsella, Risaralda.',
                'municipio_id'    => 5,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/RESERVANATURAL_LANONA/ReservaMarsella1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/RESERVANATURAL_LANONA/ReservaMarsella2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/RESERVANATURAL_LANONA/ReservaMarsella3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 19,
                'nombre'          => 'JARDÍN BOTÁNICO ALEJANDRO HUMBOLDT',
                'descripcion'     => 'Espacio educativo y natural con más de 500 especies vegetales. Incluye zonas interactivas para aprender sobre ciencia y medio ambiente. Ubicado cerca del centro, es perfecto para visitar en familia.',
                'coordenadas'     => '4.9472, -75.7486',
                'ubicacion'       => 'Avenida Principal, Barrio Villa Rica de Segovia, Marsella, Risaralda.',
                'municipio_id'    => 5,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/JARDINBOTANICOALEJANDRO/jardinMarsella1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/JARDINBOTANICOALEJANDRO/jardinMarsella2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/JARDINBOTANICOALEJANDRO/jardinMarsella3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 20,
                'nombre'          => 'IGLESIA MARÍA INMACULADA',
                'descripcion'     => 'Templo católico de estilo neogótico construido en 1905. Destaca por su imponente fachada y vitrales coloridos. Es un símbolo religioso y arquitectónico de Marsella.',
                'coordenadas'     => '4.9498, -75.9608',
                'ubicacion'       => 'Calle 10 No 9-11, Parque Principal de Marsella, Risaralda.',
                'municipio_id'    => 5,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/IGLESIAINMACULADA/IglesiaInmaculada1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/IGLESIAINMACULADA/IglesiaInmaculada2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/IGLESIAINMACULADA/IglesiaInmaculada3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 21,
                'nombre'          => 'CASCADA SUTÚ',
                'descripcion'     => 'Impresionante caída de agua de aproximadamente 80 metros de altura, rodeada de exuberante vegetación. Ideal para los amantes del senderismo y la fotografía de naturaleza. Su acceso requiere una caminata que atraviesa paisajes selváticos.',
                'coordenadas'     => '5.4190, -76.0140',
                'ubicacion'       => 'Vereda Mapay, vía San Antonio de Chamí, Mistrató, Risaralda.',
                'municipio_id'    => 6,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CASCADASUTU/CascadaSutu1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CASCADASUTU/CascadaSutu2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CASCADASUTU/CascadaSutu3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 22,
                'nombre'          => 'CASCADA LA ESTRELLA',
                'descripcion'     => 'Conformada por dos caídas de agua continuas, es un atractivo para practicar descenso en cuerda. Ubicada en un entorno natural que invita a la exploración y el disfrute del paisaje. Es un destino preferido para quienes buscan emociones en la naturaleza.',
                'coordenadas'     => '4.9547, -75.9601',
                'ubicacion'       => 'Área rural del municipio de Mistrató, Risaralda.',
                'municipio_id'    => 6,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CASCADASUTU/CascadaSutu1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CASCADASUTU/CascadaSutu2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/CASCADASUTU/CascadaSutu3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 23,
                'nombre'          => 'IGLESIA SAN JOSÉ',
                'descripcion'     => 'Templo católico de estilo neogótico construido en 1905. Destaca por su imponente fachada y vitrales coloridos. Es un símbolo religioso y arquitectónico de Mistrató.',
                'coordenadas'     => '4.9496, -75.9610',
                'ubicacion'       => 'Parque Principal de Marsella, Risaralda.',
                'municipio_id'    => 6,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/IGLESIASANJOSE/iglesiaSanjose1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/IGLESIASANJOSE/iglesiaSanjose2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/IGLESIASANJOSE/iglesiaSanjose3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 24,
                'nombre'          => 'ALTO DEL REY',
                'descripcion'     => 'Reserva ecológica de 150 hectáreas que protege bosques andinos y diversas especies de fauna. Ideal para caminatas, observación de aves y conexión con la naturaleza. Ofrece senderos ecológicos y miradores con vistas panorámicas.',
                'coordenadas'     => '4.9600, -75.9800',
                'ubicacion'       => 'Sector rural de Santuario, Risaralda.',
                'municipio_id'    => 7,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/ALTODELREY/parque-altorey1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/ALTODELREY/parque-altorey2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/ALTODELREY/parque-altorey3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 25,
                'nombre'          => 'JARDÍN BOTANICO DE BALBOA',
                'descripcion'     => 'Espacio dedicado a la conservación de la flora local y educación ambiental. Cuenta con senderos interpretativos y zonas de descanso. Es un lugar perfecto para aprender sobre la biodiversidad regional.',
                'coordenadas'     => '4.9504, -75.9615',
                'ubicacion'       => 'Casco urbano de Balboa, Risaralda.',
                'municipio_id'    => 7,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/ALTODELREY/parque-altorey1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/ALTODELREY/parque-altorey2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/ALTODELREY/parque-altorey3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 26,
                'nombre'          => 'GLAMPING TAMBORES',
                'descripcion'     => 'Alojamiento turístico ubicado en la vereda Tambores, ofreciendo una experiencia única en la naturaleza. Combina el confort con el entorno natural andino. Es una opción ideal para quienes buscan descanso y aventura.',
                'coordenadas'     => '4.888661856660609, -75.96681853420512',
                'ubicacion'       => 'Balboa, Risaralda',
                'municipio_id'    => 7,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/tambores-1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/tambores-2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/tambores-3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 27,
                'nombre'          => 'JARDIN BOTANICO GAMONRRÁ',
                'descripcion'     => 'Espacio natural que alberga una rica biodiversidad, ideal para caminatas ecológicas y observación de flora y fauna. Ofrece senderos interpretativos y zonas de descanso para los visitantes.',
                'coordenadas'     => '5.313760477533627, -75.7962748398279',
                'ubicacion'       => 'Guatica, Risaralda',
                'municipio_id'    => 8,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/JardínGamonra/gamonra1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/JardínGamonra/gamonra2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/JardínGamonra/gamonra3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 28,
                'nombre'          => 'LOS CHORROS',
                'descripcion'     => 'Conjunto de cascadas de aguas cristalinas rodeadas de vegetación, perfectas para disfrutar de un baño natural y conectar con el entorno.',
                'coordenadas'     => '5.325589237088037, -75.79734364705816',
                'ubicacion'       => 'Guatica, Risaralda',
                'municipio_id'    => 8,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/chorrosGuatica/chorrosGuatica1.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/chorrosGuatica/chorrosGuatica2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/chorrosGuatica/chorrosGuatica3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 29,
                'nombre'          => 'PARQUE PRINCIPAL DE GUATICA',
                'descripcion'     => 'El Parque Principal de Guatica es un lugar colorido y moderno, con zonas verdes, juegos y una escultura del loro orejiamarillo, símbolo de la región.',
                'coordenadas'     => '5.3154656028510425, -75.8006933624341',
                'ubicacion'       => 'Guatica, Risaralda',
                'municipio_id'    => 8,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/parqueGuatica/parqueGuatica.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/parqueGuatica/parqueGuatica2.png',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/Lugares/parqueGuatica/parqueGuatica3.png',
                ]),
                'recomendaciones' => null,
                'updated_at'      => null,
                'created_at'      => '2025-11-28',
            ],
            [
                'id'              => 50,
                'nombre'          => 'Piedras Marcadas',
                'descripcion'     => 'Es un sitio arqueológico y cultural ubicado en el Parque Regional Natural La Marcada, en las estribaciones de la Serranía del Alto del Toro en el municipio de Dosquebradas, Risaralda, Colombia.',
                'coordenadas'     => '4.815861,-75.6306367',
                'ubicacion'       => 'Dosquebradas, Risaralda',
                'municipio_id'    => 2,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'lugares/9AQfg75DxguAPLgFK8hjbz5CwwqceBKA2Dpsqsq6.webp',
                    'lugares/cHGsNBH6tfiNs02UbAEOF2KaFYxG8lRGQPfeYJfa.webp',
                    'lugares/0ak9fwOnGmQMHsmmD5CY9c4hE0aXqjacCXYlafxj.webp',
                ]),
                'recomendaciones' => null,
                'updated_at'      => '2026-02-17 12:24:39',
                'created_at'      => '2026-02-17',
            ],
            [
                'id'              => 51,
                'nombre'          => 'La Vereda del Terror',
                'descripcion'     => 'El nombre "Vereda El Terror" no se refiere oficialmente a una vereda rural reconocida en documentos geográficos o administrativos, sino más bien a una atracción de entretenimiento y eventos temáticos en el municipio.',
                'coordenadas'     => '4.8620397,-75.6791283',
                'ubicacion'       => 'Vereda del terror, Dosquebradas, Risaralda',
                'municipio_id'    => 2,
                'hoteles_cercanos' => null,
                'comentarios'     => null,
                'imagenes'        => json_encode([
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/lugares/nZ6nAVkk53SKndejMNqJqdwkMC5gzBz1ab5J9i5n.webp',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/lugares/VUZ2QDCH6cPjQ5Hi9sfwH5CH71HAB69h5gMxTvJ6.webp',
                    'https://ecoturismorisaralda.s3.us-east-2.amazonaws.com/lugares/Li5G9rG8WVRBvm6b2GwxbxU5nknt9wGZ0aobTr5b.webp',
                ]),
                'recomendaciones' => null,
                'updated_at'      => '2026-02-17 12:34:09',
                'created_at'      => '2026-02-17',
            ],
        ]);
    }
}